name: 'Zoocha Audit Bundle'
description: 'Adds audit related tools'
type: 'Feature'

install:
  - site_audit
  - reroute_email
  - hacked
  - diff
  - unused_modules
  - coder
  - security_review
  - schema
  - upgrade_status
config:
  strict: false